# Generated by Django 5.0.6 on 2024-06-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('reportero', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
